/* 주의사항 : COMTNROLEINFO쪽 ROLE_PTN 제대로 들어갔는지 확인 198번째 줄 */

INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('DUS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('WEBLOG_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BANNER_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('POPUP_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LINK_SITE_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTINFO_ID','41');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('SITE_ID','2');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('MENU_ID','2');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_CTGRYMASTER_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_CTGRY_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_NTT_NO','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_CMT_NO','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('CMMNTY_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('FILE_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTITEM_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTITEMEX_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTCNSR_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTANWPER_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTFORM_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('EVENTFANWPER_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LYT_TMPLAT_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LYT_TMPLAT_HIS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_TMPLAT_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_TMPLAT_HIS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LOGINLOG_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LYT_SOURC_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('LYT_SOURC_HIS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('MNU_HIS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_SOURC_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('BBS_SOURC_HIS_ID','1');
INSERT INTO COMTECOPSEQ (TABLE_NAME, NEXT_ID) VALUES ('VISITSCHUL_ID','1');


INSERT INTO COMTCCMMNCLCODE (CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','전자정부 프레임워크 공통서비스','전자정부 프레임워크 공통서비스','Y',NOW(),'SYSTEM',null,null);

INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM999','컨텐츠분류코드','컨텐츠분류코드','N',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM109','배너주제분류코드','배너주제분류코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','999','컨텐츠분류코드','컨텐츠분류코드','N',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM110','혼자사는세상','테스,트','Y',NOW(),'test',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM913','분야구분코드','분야구분코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM301','꾸러미구분코드','꾸러미구분코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM001','등록구분','게시판, 커뮤니티, 동호회 등록구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM020','일정구분','일정구분 부서일지정보/일지정보 상태구분','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM035','행사유형','행사/이벤트/캠페인 구분','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM910','메뉴컨텐츠구분','메뉴컨텐츠구분','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM911','컨텐츠유형코드','컨텐츠유형코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM912','게시판속성코드','게시판속성코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM201','커뮤니티구분코드','커뮤니티구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM202','승인정책코드','승인정책코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM203','재가입정책코드','재가입정책코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM005','템플릿구분코드','템플릿구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM101','배경화면구분코드','배경화면구분코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM102','대상구분코드','대상구분코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM103','시스템구분코드','시스템구분코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM006','승인유형코드','승인유형코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM007','승인상태','승인상태','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM032','작업유형코드','작업유형코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM003','대상업무유형코드','대상업무유형코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM105','QNA카테고리코드','QNA카테고리코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM108','처리상태코드','처리상태코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM104','FAQ카테고리코드','FAQ카테고리코드','N',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM107','배너구분코드','배너구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM023','사이트주제분류코드','사이트주제분류코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM800','사용자구분코드','사용자구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM990','미디어분류코드','미디어분류코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM991','변환상태코드','변환상태코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM915','메인컨텐츠','메인컨텐츠','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM918','게시판소스구분','게시판소스구분','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM919','게시판템플릿구분','게시판템플릿구분','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM916','템플릿대분류코드','템플릿대분류코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM917','템플릿중분류코드','템플릿중분류코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM920','기관유형코드','기관유형코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC','COM914','HTML소스 구분코드','HTML소스 구분코드','Y',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNCODE (CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC', 'COM017', '휴일구분', '휴일의 구분', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');


INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('직속기관','직속기관','Y','4','COM109',NOW(),'23432',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('지역교육청','지역교육청','Y','5','COM109',NOW(),'23432',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('시·도교육청','시·도교육청','Y','6','COM109',NOW(),'23432',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('타시도연구정보원','타시도연구정보원','Y','7','COM109',NOW(),'23432',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티','커뮤니티','Y','2','COM104',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사이버스쿨','사이버스쿨','Y','5','COM104',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('에듀스마켓','에듀스마켓','Y','3','COM105',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('마일리지','마일리지','Y','3','COM104',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티','커뮤니티','Y','4','COM105',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('스마트충남','스마트충남','N','1','COM109',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('교육관련','교육관련','Y','2','COM109',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기타','기타','Y','99','COM109',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('내가만든 꾸러미','내가만든 꾸러미','Y','P01','COM301',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('모태솔로','모태','Y','1','COM110',NOW(),'test',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('구매한 꾸러미','구매한 꾸러미','Y','P02','COM301',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('동영상','동영상','Y','REALM20','COM913',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('플래쉬','플래쉬','Y','REALM30','COM913',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('그래픽','그래픽','Y','REALM99','COM913',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사이트 게시판 이용등록','사이트 게시판 이용등록','Y','REGC01','COM001',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티 등록','커뮤니티 등록','Y','REGC02','COM001',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티 게시판 등록','커뮤니티 게시판 등록','Y','REGC06','COM001',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('행사및일반일정','행사및일반일정','Y','1','COM020',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('설문조사','설문조사','Y','3','COM020',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('객관식','객관식','Y','1','COM035',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('주관식','주관식','Y','2','COM035',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('없음','없음','Y','CTS01','COM910',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('일반게시판','게시판','Y','CTS02','COM910',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('프로그램','프로그램','Y','CTS04','COM910',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('IFRAME','IFRAME','Y','CTS05','COM910',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('포틀릿','포틀릿','Y','CTS06','COM910',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('앨범형게시판','앨범형게시판','Y','BBSA02','COM912',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('일반형게시판','일반형게시판','Y','BBSA03','COM912',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('일반커뮤니티','일반커뮤니티','Y','CMY01','COM201',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('학급커뮤니티','학급커뮤니티','Y','CMY02','COM201',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('자동승인','자동승인','Y','PY01','COM202',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('수동승인','수동승인','Y','PY02','COM202',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('재가입허용','재가입허용','Y','SA01','COM203',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('재가입불허','재가입불허','Y','SA02','COM203',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('홈페이지템플릿','홈페이지템플릿','Y','sit','COM005',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티템플릿','커뮤니티템플릿','Y','cmy','COM005',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('스마트충남','스마트충남','Y','BCRN01','COM101',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('계절','계절','Y','BCRN02','COM101',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('배경','배경','Y','BCRN','COM102',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('메뉴','메뉴','Y','MNU','COM102',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('시스템','시스템','Y','SYS','COM103',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('개인','개인','Y','INDVDL','COM103',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티등록','커뮤니티등록','Y','CF01','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티삭제','커뮤니티삭제','Y','CF02','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티운영자등록','커뮤니티운영자등록','Y','CF05','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티운영자삭제','커뮤니티운영자삭제','Y','CF06','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('게시판이용등록','게시판이용등록','Y','CF09','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('게시판삭제','게시판삭제','Y','CF10','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티사용자등록','커뮤니티사용자등록','Y','CF11','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티사용자탈퇴','커뮤니티사용자탈퇴','Y','CF12','COM006',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('승인요청','승인요청','Y','AP01','COM007',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('승인허가','승인허가','Y','AP02','COM007',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('승인반려','승인반려','Y','AP03','COM007',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('회원가입','회원가입','Y','WC01','COM032',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사용자등록','사용자등록','Y','WC02','COM032',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('회원탈퇴','회원탈퇴','Y','WC03','COM032',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사용자삭제','사용자삭제','Y','WC04','COM032',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('게시판','게시판','Y','BBS','COM003',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티','커뮤니티','Y','CMY','COM003',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('회원가입','회원가입','Y','1','COM105',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기타','기타','Y','99','COM105',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('접수대기','접수대기','Y','QA01','COM108',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('처리중','처리중','Y','QA02','COM108',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('처리완료','처리완료','Y','QA03','COM108',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('회원정보','회원정보','Y','1','COM104',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기타','기타','Y','99','COM104',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('하단배너','하단배너','Y','BAN004','COM107',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('관련사이트','관련사이트','Y','1','COM023',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('부속기관','부속기관','Y','2','COM023',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기타','기타','Y','CMY05','COM201',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('edus마켓','edus마켓','Y','4','COM104',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사이버스쿨','사이버스쿨','Y','2','COM105',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('파워포인트','파워포인트','Y','1','COM999',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('동영상','동영상','Y','MVP','COM990',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('사진','사진','Y','PHOTO','COM990',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('음원','음원','Y','AUDIO','COM990',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('문서','문서','Y','DOC','COM990',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('준비','준비','Y','READY','COM991',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('진행중','진행중','Y','RUNNING','COM991',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('완료','완료','Y','COMPLETE','COM991',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('에러','에러','Y','ERROR','COM991',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('게시판','게시판','Y','SMCTS01','COM915',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('공통','공통','Y','BSSE_01','COM918',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('공통','공통','Y','BTSE_01','COM919',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('통합캘린더','통합캘린더','Y','PRGCAL','COM911',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티','커뮤니티','Y','PRGCMY','COM911',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('VOD서비스 게시판 등록','VOD서비스 게시판 등록','Y','REGC90','COM001',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('홈페이지','홈페이지','Y','sit','COM916',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('커뮤니티','커뮤니티','Y','cmy','COM916',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기관','기관','Y','1','COM917',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('기관','기관','Y','1','COM920',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('민원상담게시판','민원상담게시판','Y','BBSA11','COM912',NOW(),'admin',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('HTML','HTML','Y','HTML','COM914',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('JSP','JSP','Y','JSP','COM914',NOW(),'SYSTEM',NULL,NULL);
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('COM017', '01', '법정휴일', '법정휴일', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('COM017', '02', '법정공휴일', '법정공휴일', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID) VALUES ('COM017', '03', '임시공휴일', '임시공휴일', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('01','모든사용자','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('02','시민','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('04','학부모','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('06','학생','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('08','교사','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('10','업무관리자','',NOW());
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE) VALUES ('99','통합관리자','',NOW());


INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('01','02');
INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('02','04');
INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('04','06');
INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('06','08');
INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('08','10');
INSERT INTO COMTNROLES_HIERARCHY (PARENT_ROLE, CHILD_ROLE) VALUES ('10','99');

INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_DC, ROLE_CREAT_DE, ROLE_NM, ROLE_PTN, ROLE_TYP, ROLE_SORT) VALUES ('web-000001','관리자접근권한','2011-11-29','보안등급이상','\A/mng/.*\Z','url','2');

INSERT INTO COMTNAUTHORROLERELATE (CREAT_DT, AUTHOR_CODE, ROLE_CODE) VALUES ( NOW(), '10', 'web-000001' );

INSERT INTO COMTNMBER (USER_ID, USER_SE_CODE, PASSWORD, USER_NM, EMAIL_ADRES, TLPHON_NO, MOBLPHON_NO, ZIP, ADRES, ADRES_DETAIL, BRTHDY, SLRCLD_LRR_CODE, SEXDSTN, EMAIL_RECPTN_AT, MOBLPHON_RECPTN_AT, PHOTO_ORIGINAL_FILE_NM, PHOTO_STRE_FILE_NM, DELETE_AT, DELETE_PNTTM, DELETE_RESN, CONFM_AT, CONFM_PNTTM, CREDT_ID, CRTFCT_DN, CRTFCT_SERIAL, SITE_ID, FRST_REGIST_IP, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDUSR_PNTTM) 
   VALUES ('admin','99','6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b','관리자','16449420@emtmail.kr','02-1644-9420','010-0000-0000','111222','333','4444','','','','','','','','N',NOW(),'1','Y',NOW(),'20121123111910','','','SITE_000000000000001','',NOW(),null,null);

INSERT INTO COMTNSITEINFO (
   SITE_ID, SITE_NM, SITE_URL, 
   FRST_REGISTER_PNTTM, FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, 
   LAST_UPDUSR_ID, USE_AT, ACTVTY_AT, 
   UPEND_LOGO_FILE_NM, LPT_LOGO_FILE_NM, LYT_TMPLAT_ID, 
   ADRES_FILE_NM, ADRES_REPLC_TEXT, INDVDLINFO_POLICY, 
   USE_STPLAT, EMAIL_COLCT_POLICY, MOBILE_USE_AT, 
   CMY_TMPLAT_ID, CPYRHT_STTEMNT_SVC, INSTT_CODE, 
   BRWSR_SJ, TLPHON_NO, FAX_NO, 
   ADRES, MOUSE_SCRTY_APPLC_AT, KYBRD_SCRTY_APPLC_AT, 
   DPLCT_LOGIN_PERM_AT, PASSWORD_MUMM_LT, PASSWORD_MXMM_LT, 
   PASSWORD_NUMBER_POLICY_AT, PASSWORD_CHRCTR_POLICY_AT, PASSWORD_SPCLCHRCTR_POLICY_AT, 
   PASSWORD_CHANGE_CYCLE, LYT_SOURC_ID, CMY_SOURC_ID, 
   REPRSNT_IMAGE_FILE_NM, SLOGAN_FILE_NM, SLOGAN_REPLC_TEXT, 
   LA, LO) 
VALUES ('SITE_000000000000001','메인사이트','dev.cait.ca:8080',NOW(),'admin',NULL,NULL,'Y','Y','','','LYTTMP_0000000000001','','대전광역시 유성구 노은동 550-9 미란빌딩 2층',
'<p>학교명 : $SITE_NM$ <br />전화번호 : $PHONE_NO$ <br />팩스번호 : $FAX_NO$ <br />개인정보처리방침</p>',
'<p>학교명 : $SITE_NM$ <br />전화번호 : $PHONE_NO$ <br />팩스번호 : $FAX_NO$ <br />$SITE_NM$ 가입약관</p>',
'<p>학교명 : $SITE_NM$ <br />전화번호 : $PHONE_NO$ <br />팩스번호 : $FAX_NO$ <br />$SITE_NM$ 이메일수집거부</p>',
'Y','','<p>학교명 : $SITE_NM$ <br />전화번호 : $PHONE_NO$ <br />팩스번호 : $FAX_NO$ <br />$SITE_NM$ 저작권신고서비스</p>','','개발','000-0000-0000','000-0000-0000','대전광역시 유성구 노은동 550-9 미란빌딩 2층','N','N','Y','4','20','Y','Y','Y','6','LYTSRC_0000000000001','','SITE_201210250244444490.jpg','','슬로건대체텍스트','','');

/* 기본 메뉴 생성 */
INSERT INTO COMTNSITEMNU (MENU_NM, MENU_ID, UPPER_MENU_ID, HTML_CN, EXPSR_USE_AT, USE_AT, HTML_USE_AT, CNTNTS_TY_CODE, URL, COMPOSITION_TY_CODE, PROGRM_ID, NWD_AT, STYLE_CN, SCRIPT_CN, FRST_REGISTER_PNTTM, 
FRST_REGISTER_ID, LAST_UPDUSR_PNTTM, LAST_UPDUSR_ID, SORT_ORDR, MOBILE_USE_AT, IMAGE_FILE_NM, SITE_ID, SYS_TY_CODE, STDNT_USE_AT, STDNPRNT_USE_AT, PROFSR_USE_AT, GENERAL_USE_AT, MOBILE_STYLE_CN, MOBILE_SCRIPT_CN, 
MOBILE_HTML_CN, HTMLSOURC_TY_CODE, MOBILE_HTMLSOURC_TY_CODE, ATCH_FILE_ID, MOBILE_ATCH_FILE_ID, PROGRM_FACTR, MENU_LEVEL) 
VALUES ('홈페이지','MNU_0000000000000001',NULL,'','Y','Y','Y','CTS01','','CNTNTS','','N','','',NOW(),'',NOW(),'admin','0','N','','SITE_000000000000001','SYS01','N','N','N','N','JSP','HTML','','','','','','',0);

/* 휴일 지정이 필요할때 테이블 생성하고 넣어라*/
/*
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  1, '20130101', '신정', '설(신정)', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  2, '20130209', '설날', '설연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  3, '20130210', '설날', '설연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  4, '20130211', '설날', '설연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  5, '20130301', '삼일절', '삼일절', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  6, '20130505', '어린이날', '어린이날', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  7, '20130517', '석가탄신일', '석가탄신일', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  8, '20130606', '현충일', '현충일', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  9, '20130815', '광복절', '광복절', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  10, '20130918', '추석', '추석연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  11, '20130919', '추석', '추석연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  12, '20130920', '추석', '추석연휴', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  13, '20131003', '개천절', '개천절', '02', NOW(), 'SYSTEM' );
INSERT INTO COMTNRESTDE ( RESTDE_NO, RESTDE_DE, RESTDE_NM, RESTDE_DC, RESTDE_SE_CODE, FRST_REGISTER_PNTTM, FRST_REGISTER_ID) VALUES (  14, '20131225', '성탄절', '성탄절', '02', NOW(), 'SYSTEM' );
*/